name = "FlameGraphs"
uuid = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.1.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
LeftChildRightSiblingTrees = "1d6d02ad-be62-4b6b-8a6d-2f90e265016e"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[compat]
AbstractTrees = "0.3"
Colors = "0.9, 0.10, 0.11"
FixedPointNumbers = "0.6.1, 0.7"
IndirectArrays = "0.5"
LeftChildRightSiblingTrees = "0.1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
